name: Create repo
description: 'Creates repo from rpms from a release'
inputs:
  component_path:
    description: 'Github repository path for the component'
    required: true
    type: string
  component_version:
    description: 'The version to make repository of'
    required: true
    type: string
  deploy_branch:
    description: 'Which branch to deploy the repodata to'
    default: 'gh-pages'
    type: string
  deploy_basepath:
    description: 'Which path to deploy the repodata to'
    default: 'repo'
    type: string
runs:
  using: composite
  steps:
    # Try checking out deployment branch
    - name: Fetch deployment branch
      id: checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        repository: ${{ github.repository }}
        ref: ${{ inputs.deploy_branch }}
        sparse-checkout: |
          ${{ inputs.deploy_basepath }}/
        path: "${{ runner.temp }}"
      continue-on-error: true
    # Checkout main if deployment branch does not exist
    - name: Fetch main branch
      if: steps.checkout.outcome == 'failure'
      uses: actions/checkout@v6
      with:
        fetch-depth: 0
        path: "${{ runner.temp }}"
    # Create deployment directories
    - name: Prepare repository deployment dirs
      run: mkdir -p "${{ runner.temp }}/deployment/${{ inputs.deploy_basepath }}/${{ inputs.component_version }}"
      shell: bash
    # Install dependencies
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get --yes install createrepo-c
      shell: bash
    # Download artifact(s)
    - name: Download release
      run: gh release download --repo "${{ inputs.component_path }}" --pattern "*.rpm" --dir "${{ runner.temp }}/workdir/${{ inputs.component_version }}" "${{ inputs.component_version }}"
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
    # Generate repository files
    - name: Generate repository files
      run: cd "${{ runner.temp }}/" && createrepo_c --no-database --baseurl=https://www.github.com --location-prefix="https://github.com/${{ inputs.component_path }}/releases/download/" --outputdir="${{ runner.temp }}/deployment/${{ inputs.deploy_basepath }}/${{ inputs.component_version }}" workdir/
      shell: bash
    # Normalize path for repofile
    - name: Normalize repository information
      run: printf "NORMALIZED_PATH=%q\n" "$(sed 's,/,-,g' <<< '${{ inputs.component_path }}-${{ inputs.component_version }}')" >> $GITHUB_ENV
      shell: bash
    # Create repofile
    - name: Create .repo file
      run: |
        echo '[${{ env.NORMALIZED_PATH }}]
        name=${{ env.NORMALIZED_PATH }}
        baseurl=https://raw.githubusercontent.com/${{ github.repository }}/refs/heads/${{ inputs.deploy_branch }}/${{ inputs.deploy_basepath }}/${{ inputs.component_version }}
        gpgcheck=0
        enabled=1' > "${{ runner.temp }}/deployment/${{ inputs.deploy_basepath }}/${{ inputs.component_version }}/${{ env.NORMALIZED_PATH }}.repo"
      shell: bash
    # Deploy current repository
    - name: Deploy base repository files
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: "${{ runner.temp }}/deployment/${{ inputs.deploy_basepath }}/${{ inputs.component_version }}"
        target-folder: "${{ inputs.deploy_basepath }}/${{ inputs.component_version }}"
        branch: "${{ inputs.deploy_branch }}"
        token: ${{ secrets.GITHUB_TOKEN }}
    # Merge repos
    - name: Merge repositories
      run: cd "${{ runner.temp }}/" && mergerepo_c --all --no-database $(find "${{ inputs.deploy_basepath }}/" -maxdepth 1 -type d -not -name releases -not -name "${{ inputs.deploy_basepath }}" -printf "--repo=%p ") --outputdir "${{ runner.temp }}/deployment/${{ inputs.deploy_basepath }}/releases"
      shell: bash
    # Normalize path for repofile
    - name: Normalize repository information
      run: printf "NORMALIZED_PATH_RELEASES=%q\n" "$(sed 's,/,-,g' <<< '${{ inputs.component_path }}-releases')" >> $GITHUB_ENV
      shell: bash
    # Create repofile
    - name: Create .repo file
      run: |
        echo '[${{ env.NORMALIZED_PATH_RELEASES }}]
        name=${{ env.NORMALIZED_PATH_RELEASES }}
        baseurl=https://raw.githubusercontent.com/${{ github.repository }}/refs/heads/${{ inputs.deploy_branch }}/${{ inputs.deploy_basepath }}/releases
        gpgcheck=0
        enabled=1' > "${{ runner.temp }}/deployment/${{ inputs.deploy_basepath }}/releases/${{ env.NORMALIZED_PATH_RELEASES }}.repo"
      shell: bash
    # Deploy releases repository
    - name: Deploy releases repository files
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: "${{ runner.temp }}/deployment/${{ inputs.deploy_basepath }}/releases"
        target-folder: "${{ inputs.deploy_basepath }}/releases"
        branch: "${{ inputs.deploy_branch }}"
        token: ${{ secrets.GITHUB_TOKEN }}
