name: trigger

on: [ push ]
permissions: write-all
jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: dl
        run: |
          gh release download --repo "strongestnumber9/rlp_07" --pattern "*.rpm" --dir "rpm" "1.0.21";
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Update
        uses: StrongestNumber9/dfg_01@package_manager_compat
        with:
          from_repository: "strongestnumber9/rlp_07"
          from_version: 1.0.21
          to_repository: "${{ github.repository_owner }}/pkg_01"
          to_path: "proxyable/default"
          deploy_key: "${{ secrets.PKG_01_DEPLOY_KEY }}"
          files: rpm/*.rpm
          repo_name: proxyable-default
          gpg_public_key: "${{ secrets.RPM_SIGNING_PUBLIC_KEY }}"
        env:
          has_deploy_key: ${{ secrets.PKG_01_DEPLOY_KEY != '' }}
      - name: Update
        uses: StrongestNumber9/dfg_01@package_manager_compat
        with:
          from_repository: "strongestnumber9/rlp_07"
          from_version: 1.0.21
          to_repository: "${{ github.repository_owner }}/pkg_01"
          to_path: "proxyable/baseurl"
          deploy_key: "${{ secrets.PKG_01_DEPLOY_KEY }}"
          files: rpm/*.rpm
          gpg_public_key: "${{ secrets.RPM_SIGNING_PUBLIC_KEY }}"
          repo_name: proxyable-baseurl
          repo_baseurl: "http://127.0.0.1:8081/repository/teragrep"
        env:
          has_deploy_key: ${{ secrets.PKG_01_DEPLOY_KEY != '' }}
        if: ${{ env.has_deploy_key == 'true' }}
      - name: Update
        uses: StrongestNumber9/dfg_01@package_manager_compat
        with:
          from_repository: "strongestnumber9/rlp_07"
          from_version: 1.0.21
          to_repository: "${{ github.repository_owner }}/pkg_01"
          to_path: "proxyable/location-prefix"
          deploy_key: "${{ secrets.PKG_01_DEPLOY_KEY }}"
          files: rpm/*.rpm
          gpg_public_key: "${{ secrets.RPM_SIGNING_PUBLIC_KEY }}"
          repo_name: proxyable-location-prefix
          repo_baseurl: "http://127.0.0.1:8081/repository/teragrep"
          location_prefix: "packages/"
        env:
          has_deploy_key: ${{ secrets.PKG_01_DEPLOY_KEY != '' }}
        if: ${{ env.has_deploy_key == 'true' }}
