name: trigger

on: [ push ]
permissions: write-all
jobs:
  create_repo:
    runs-on: ubuntu-latest
    steps:
      - name: dl
        run: |
          gh release download --repo "teragrep/rlp_10" --pattern "*.rpm" --dir "rpm" "1.0.0";
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Update
        uses: StrongestNumber9/dfg_01@make_proxyable
        with:
          from_repository: teragrep/rlp_10
          from_version: 1.0.0
          to_repository: "${{ github.repository_owner }}/pkg_01"
          to_path: "links/no-baseurl-no-prefix"
          deploy_key: "${{ secrets.PKG_01_DEPLOY_KEY }}"
          files: rpm/*.rpm
          repo_name: no-baseurl-no-prefix
          gpg_public_key: "${{ secrets.RPM_SIGNING_PUBLIC_KEY }}"
        env:
          has_deploy_key: ${{ secrets.PKG_01_DEPLOY_KEY != '' }}
      - name: Update
        uses: StrongestNumber9/dfg_01@make_proxyable
        with:
          from_repository: "${{ github.repository }}"
          from_version: "${{ github.run_id }}"
          to_repository: "${{ github.repository_owner }}/pkg_01"
          to_path: "links/with-baseurl-no-prefix-no-append"
          deploy_key: "${{ secrets.PKG_01_DEPLOY_KEY }}"
          files: rpm/*.rpm
          gpg_public_key: "${{ secrets.RPM_SIGNING_PUBLIC_KEY }}"
          repo_name: with-baseurl-no-prefix-no-append
          repo_baseurl: "http://127.0.0.1:8081/repository/teragrep"
        env:
          has_deploy_key: ${{ secrets.PKG_01_DEPLOY_KEY != '' }}
        if: ${{ env.has_deploy_key == 'true' }}
      - name: Update
        uses: StrongestNumber9/dfg_01@make_proxyable
        with:
          from_repository: "${{ github.repository }}"
          from_version: "${{ github.run_id }}"
          to_repository: "${{ github.repository_owner }}/pkg_01"
          to_path: "links/with-baseurl-with-prefix-no-append"
          deploy_key: "${{ secrets.PKG_01_DEPLOY_KEY }}"
          files: rpm/*.rpm
          gpg_public_key: "${{ secrets.RPM_SIGNING_PUBLIC_KEY }}"
          repo_name: with-baseurl-with-prefix-no-append
          repo_baseurl: "http://127.0.0.1:8081/repository/teragrep"
          repo_baseurl_append_path: false
          location_prefix: packages
        env:
          has_deploy_key: ${{ secrets.PKG_01_DEPLOY_KEY != '' }}
        if: ${{ env.has_deploy_key == 'true' }}
      - name: Update
        uses: StrongestNumber9/dfg_01@make_proxyable
        with:
          from_repository: "${{ github.repository }}"
          from_version: "${{ github.run_id }}"
          to_repository: "${{ github.repository_owner }}/pkg_01"
          to_path: "links/with-baseurl-with-prefix-with-append"
          deploy_key: "${{ secrets.PKG_01_DEPLOY_KEY }}"
          files: rpm/*.rpm
          gpg_public_key: "${{ secrets.RPM_SIGNING_PUBLIC_KEY }}"
          repo_name: with-baseurl-with-prefix-with-append
          repo_baseurl: "http://127.0.0.1:8081/repository/teragrep"
          repo_baseurl_append_path: true
          location_prefix: packages
        env:
          has_deploy_key: ${{ secrets.PKG_01_DEPLOY_KEY != '' }}
        if: ${{ env.has_deploy_key == 'true' }}
